{
  "name": "Rocket chat",
  "nodes": [
    {
      "parameters": {
        "rules": {
          "values": [
            {
              "conditions": {
                "options": {
                  "caseSensitive": true,
                  "leftValue": "",
                  "typeValidation": "strict",
                  "version": 2
                },
                "conditions": [
                  {
                    "leftValue": "={{ $json.body.text }}",
                    "rightValue": "",
                    "operator": {
                      "type": "string",
                      "operation": "exists",
                      "singleValue": true
                    },
                    "id": "8cbb657e-a58b-4bb8-85b3-3a6f69ce3dd4"
                  }
                ],
                "combinator": "and"
              },
              "renameOutput": true,
              "outputKey": "Text"
            },
            {
              "conditions": {
                "options": {
                  "caseSensitive": true,
                  "leftValue": "",
                  "typeValidation": "strict",
                  "version": 2
                },
                "conditions": [
                  {
                    "id": "c0d72019-567f-447e-bdef-393a175d1d98",
                    "leftValue": "={{ $json.body.file_url }}",
                    "rightValue": "",
                    "operator": {
                      "type": "string",
                      "operation": "exists",
                      "singleValue": true
                    }
                  }
                ],
                "combinator": "and"
              },
              "renameOutput": true,
              "outputKey": "File"
            }
          ]
        },
        "options": {}
      },
      "type": "n8n-nodes-base.switch",
      "typeVersion": 3.2,
      "position": [
        -60,
        -160
      ],
      "id": "6c2b82c6-5a22-46bb-bc92-465fad18d2de",
      "name": "Switch"
    },
    {
      "parameters": {
        "promptType": "define",
        "text": "={{ $json.body.text }} You are an AI agent integrated with powerful search tools. For every incoming query answer using snowflake tools, If the tools provide a valid response, return that information to the user. However, if no relevant results are found or if the tool query fails, then seamlessly switch to using the chat modal to generate a comprehensive answer. Always prioritize tool-based responses, but ensure a complete and helpful reply by falling back to the chat modal when needed, and return the answer in which ever the language the query is asked use chat model.",
        "options": {}
      },
      "type": "@n8n/n8n-nodes-langchain.agent",
      "typeVersion": 1.8,
      "position": [
        1500,
        -200
      ],
      "id": "9c472588-b8b4-448b-88b0-5eb45e08832c",
      "name": "AI Agent"
    },
    {
      "parameters": {
        "model": "llama-3.3-70b-versatile",
        "options": {}
      },
      "type": "@n8n/n8n-nodes-langchain.lmChatGroq",
      "typeVersion": 1,
      "position": [
        1420,
        60
      ],
      "id": "42acd9f2-2805-4736-a842-642ea1f40f5b",
      "name": "Groq Chat Model",
      "credentials": {
        "groqApi": {
          "id": "s0GCyKkBux7AZbFW",
          "name": "Groq account 2"
        }
      }
    },
    {
      "parameters": {
        "sessionIdType": "customKey",
        "sessionKey": "={{ $('Wisdom Sage').item.json.headers['x-forwarded-for'] }}"
      },
      "type": "@n8n/n8n-nodes-langchain.memoryBufferWindow",
      "typeVersion": 1.3,
      "position": [
        1580,
        60
      ],
      "id": "9adab46f-6d4f-444e-b7b8-ed2411cbc41a",
      "name": "Simple Memory"
    },
    {
      "parameters": {
        "inputDataFieldName": "file_47.mp3",
        "name": "data",
        "driveId": {
          "__rl": true,
          "value": "My Drive",
          "mode": "list",
          "cachedResultName": "My Drive",
          "cachedResultUrl": "https://drive.google.com/drive/my-drive"
        },
        "folderId": {
          "__rl": true,
          "value": "1E-ZyECgq1ele17fcDhOwUdfPZip0begk",
          "mode": "list",
          "cachedResultName": "temp",
          "cachedResultUrl": "https://drive.google.com/drive/folders/1E-ZyECgq1ele17fcDhOwUdfPZip0begk"
        },
        "options": {}
      },
      "type": "n8n-nodes-base.googleDrive",
      "typeVersion": 3,
      "position": [
        620,
        40
      ],
      "id": "d82a6afb-e4a2-44d1-8b91-d2aa7704d27e",
      "name": "Upload",
      "credentials": {
        "googleDriveOAuth2Api": {
          "id": "eEKvXP4mlOcQRy6d",
          "name": "Google Drive account"
        }
      }
    },
    {
      "parameters": {
        "operation": "download",
        "fileId": {
          "__rl": true,
          "value": "={{ $json.id }}",
          "mode": "id"
        },
        "options": {
          "fileName": "file.mp3"
        }
      },
      "type": "n8n-nodes-base.googleDrive",
      "typeVersion": 3,
      "position": [
        800,
        40
      ],
      "id": "60bc6790-b347-4b8d-8491-45e85ee28cf6",
      "name": "Download",
      "credentials": {
        "googleDriveOAuth2Api": {
          "id": "eEKvXP4mlOcQRy6d",
          "name": "Google Drive account"
        }
      }
    },
    {
      "parameters": {
        "operation": "deleteFile",
        "fileId": {
          "__rl": true,
          "value": "={{ $('Download').item.json.id }}",
          "mode": "id"
        },
        "options": {}
      },
      "type": "n8n-nodes-base.googleDrive",
      "typeVersion": 3,
      "position": [
        2320,
        40
      ],
      "id": "4364272c-cb65-4b8e-8ca1-40d96a34826a",
      "name": "Delete",
      "credentials": {
        "googleDriveOAuth2Api": {
          "id": "eEKvXP4mlOcQRy6d",
          "name": "Google Drive account"
        }
      }
    },
    {
      "parameters": {
        "method": "POST",
        "url": "http://192.168.1.11/hooks/67ee1f4cd8559cbecc4e2c47/MwGyNzcZaAXuZq9DQRPLYXuuj6CPrjKz2Es3n5rPd7vwbHeE",
        "sendBody": true,
        "specifyBody": "json",
        "jsonBody": "={\n    \"text\":\"{{ $json.output }}\"\n} ",
        "options": {}
      },
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.2,
      "position": [
        1980,
        -200
      ],
      "id": "69f71823-c8d1-40f7-b870-7374626f832f",
      "name": "Response to Rocket Chat"
    },
    {
      "parameters": {
        "operation": "executeQuery",
        "query": "CALL SEARCH_TEXT_PROC('{{ $json.body.text }}');"
      },
      "type": "n8n-nodes-base.snowflakeTool",
      "typeVersion": 1,
      "position": [
        1880,
        60
      ],
      "id": "4980cda3-191e-4ba7-a8bc-f0f564b3f3f2",
      "name": "Snowflake",
      "credentials": {
        "snowflake": {
          "id": "EdVeecYEc0cCF5hK",
          "name": "Snowflake account 3"
        }
      }
    },
    {
      "parameters": {
        "conditions": {
          "options": {
            "caseSensitive": true,
            "leftValue": "",
            "typeValidation": "strict",
            "version": 2
          },
          "conditions": [
            {
              "id": "9d1b1905-b28a-4953-b07a-898972164f00",
              "leftValue": "={{ $('Switch').item.json.body.file_url }}",
              "rightValue": "",
              "operator": {
                "type": "string",
                "operation": "exists",
                "singleValue": true
              }
            }
          ],
          "combinator": "and"
        },
        "options": {}
      },
      "type": "n8n-nodes-base.filter",
      "typeVersion": 2.2,
      "position": [
        2140,
        -80
      ],
      "id": "dd13df26-fe77-4c13-8f4d-3bb4780249e7",
      "name": "Filter"
    },
    {
      "parameters": {
        "url": "=http://192.168.1.23{{ $json.body.file_url }}",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {}
          ]
        },
        "options": {
          "response": {
            "response": {
              "responseFormat": "file",
              "outputPropertyName": "file_47.mp3"
            }
          }
        }
      },
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.2,
      "position": [
        520,
        -100
      ],
      "id": "df1e7a97-5f3b-4935-9b56-9600beae0b7b",
      "name": "Get Image File"
    },
    {
      "parameters": {
        "url": "http://192.168.1.23/file-upload/67ff3eafaa9e1e694b5e98a7/hello-46355%20(1).mp3",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {}
          ]
        },
        "options": {
          "response": {
            "response": {
              "responseFormat": "file",
              "outputPropertyName": "file_47.mp3"
            }
          }
        }
      },
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.2,
      "position": [
        420,
        40
      ],
      "id": "8143f872-fee8-4db9-8d55-df517291938c",
      "name": "Get Audio File"
    },
    {
      "parameters": {
        "resource": "image",
        "operation": "analyze",
        "modelId": {
          "__rl": true,
          "value": "chatgpt-4o-latest",
          "mode": "list",
          "cachedResultName": "CHATGPT-4O-LATEST"
        },
        "inputType": "base64",
        "binaryPropertyName": "file_47.mp3",
        "options": {}
      },
      "type": "@n8n/n8n-nodes-langchain.openAi",
      "typeVersion": 1.8,
      "position": [
        900,
        -100
      ],
      "id": "2acc9aee-3bfb-4303-8876-6c62536f171b",
      "name": "Image Analyzer",
      "credentials": {
        "openAiApi": {
          "id": "tj1IVwQWko60mtQB",
          "name": "OpenAi account 2"
        }
      }
    },
    {
      "parameters": {
        "resource": "audio",
        "operation": "transcribe",
        "options": {}
      },
      "type": "@n8n/n8n-nodes-langchain.openAi",
      "typeVersion": 1.8,
      "position": [
        1020,
        40
      ],
      "id": "caa6953f-dd43-4fe5-9128-091982f17ff9",
      "name": "Audio Transcriber",
      "credentials": {
        "openAiApi": {
          "id": "tj1IVwQWko60mtQB",
          "name": "OpenAi account 2"
        }
      }
    },
    {
      "parameters": {
        "jsCode": "// Loop over input items and add a new field called 'myNewField' to the JSON of each one\nfor (const item of $input.all()) {\n  item.json.myNewField = 1;\n}\n\nreturn $input.all();"
      },
      "type": "n8n-nodes-base.code",
      "typeVersion": 2,
      "position": [
        1280,
        -200
      ],
      "id": "9edfa0c2-16a3-48ed-98a9-84ffde113424",
      "name": "Agent Input"
    },
    {
      "parameters": {
        "rules": {
          "values": [
            {
              "conditions": {
                "options": {
                  "caseSensitive": true,
                  "leftValue": "",
                  "typeValidation": "strict",
                  "version": 2
                },
                "conditions": [
                  {
                    "leftValue": "={{ $json.body.file_name }}",
                    "rightValue": ".jpg",
                    "operator": {
                      "type": "string",
                      "operation": "endsWith"
                    },
                    "id": "c745cecf-18e7-4565-9691-b59502fdcfb5"
                  }
                ],
                "combinator": "and"
              },
              "renameOutput": true,
              "outputKey": "Image"
            },
            {
              "conditions": {
                "options": {
                  "caseSensitive": true,
                  "leftValue": "",
                  "typeValidation": "strict",
                  "version": 2
                },
                "conditions": [
                  {
                    "id": "0a4eadca-a0af-4ccc-a0d5-741a5c77a0ec",
                    "leftValue": "={{ $json.body.file_name }}",
                    "rightValue": ".jpg",
                    "operator": {
                      "type": "string",
                      "operation": "notEndsWith"
                    }
                  }
                ],
                "combinator": "and"
              },
              "renameOutput": true,
              "outputKey": "Audio"
            }
          ]
        },
        "options": {}
      },
      "type": "n8n-nodes-base.switch",
      "typeVersion": 3.2,
      "position": [
        140,
        -80
      ],
      "id": "7c58b2e8-4d36-4d46-974a-45314b939ee3",
      "name": "Switch1"
    },
    {
      "parameters": {
        "resource": "search",
        "query": "=SELECT SDO_Current_Year_Target__c FROM Account WHERE Name = '{{ $('Agent Input').item.json.body.text }}'"
      },
      "type": "n8n-nodes-base.salesforceTool",
      "typeVersion": 1,
      "position": [
        1740,
        60
      ],
      "id": "95b1b1ef-c981-4169-b874-e7e5927a0d9a",
      "name": "Salesforce1",
      "credentials": {
        "salesforceOAuth2Api": {
          "id": "m7jmPkYeIJKHSXAr",
          "name": "Salesforce account"
        }
      },
      "disabled": true
    },
    {
      "parameters": {
        "httpMethod": "POST",
        "path": "806f1553-6b37-4189-94cb-1c4caa1cdbd8",
        "options": {
          "rawBody": false
        }
      },
      "type": "n8n-nodes-base.webhook",
      "typeVersion": 2,
      "position": [
        -300,
        -160
      ],
      "id": "9fe25476-7dc2-4039-aa12-88c60f3dbc8a",
      "name": "Wisdom Sage",
      "webhookId": "806f1553-6b37-4189-94cb-1c4caa1cdbd8"
    }
  ],
  "pinData": {},
  "connections": {
    "Switch": {
      "main": [
        [
          {
            "node": "Agent Input",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "Switch1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Groq Chat Model": {
      "ai_languageModel": [
        [
          {
            "node": "AI Agent",
            "type": "ai_languageModel",
            "index": 0
          }
        ]
      ]
    },
    "AI Agent": {
      "main": [
        [
          {
            "node": "Response to Rocket Chat",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Simple Memory": {
      "ai_memory": [
        [
          {
            "node": "AI Agent",
            "type": "ai_memory",
            "index": 0
          }
        ]
      ]
    },
    "Upload": {
      "main": [
        [
          {
            "node": "Download",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Download": {
      "main": [
        [
          {
            "node": "Audio Transcriber",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Response to Rocket Chat": {
      "main": [
        [
          {
            "node": "Filter",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Snowflake": {
      "ai_tool": [
        [
          {
            "node": "AI Agent",
            "type": "ai_tool",
            "index": 0
          }
        ]
      ]
    },
    "Filter": {
      "main": [
        [
          {
            "node": "Delete",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Get Image File": {
      "main": [
        [
          {
            "node": "Image Analyzer",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Get Audio File": {
      "main": [
        [
          {
            "node": "Upload",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Image Analyzer": {
      "main": [
        [
          {
            "node": "Agent Input",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Audio Transcriber": {
      "main": [
        [
          {
            "node": "Agent Input",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Agent Input": {
      "main": [
        [
          {
            "node": "AI Agent",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Switch1": {
      "main": [
        [
          {
            "node": "Get Image File",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "Get Audio File",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Salesforce1": {
      "ai_tool": [
        [
          {
            "node": "AI Agent",
            "type": "ai_tool",
            "index": 0
          }
        ]
      ]
    },
    "Wisdom Sage": {
      "main": [
        [
          {
            "node": "Switch",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {
    "executionOrder": "v1"
  },
  "versionId": "6feab487-4ac5-4417-9cd3-9d8753b21b89",
  "meta": {
    "templateCredsSetupCompleted": true,
    "instanceId": "dd98a6e9c4d6d6637c592f7b142c200f96537e89aebdd6b513bee838551cea65"
  },
  "id": "tnty9rO7LsDSrqqs",
  "tags": []
}
